name: fepa
channels:
  - salilab
  - conda-forge
  - omnia
dependencies:
  - python=3.10
  - plumed
  - modeller
  - mdaencore
  - ipykernel
  - numpy
  - cython
  - openmm
  - openmmforcefields
  - numba
  - pytest
  